argparse_cfg:
  gpus: 
    bind_to: processor_cfg.gpus
    help: number of gpus
  work_dir: 
    bind_to: processor_cfg.work_dir
    help: the dir to save logs and models
  batch_size: 
    bind_to: processor_cfg.batch_size
  resume_from:
    bind_to: processor_cfg.resume_from
    help: the checkpoint file to resume from



processor_cfg: 
  name: '.processor.translearning.train'

  # model setting
  model_cfg:
    name: '.models.backbones.ST_GCN'
    in_channels: 3
    num_class: 2
    dropout: 0.5
    edge_importance_weighting: True
    graph_cfg:
      layout: 'ntu-rgb+d'
      strategy: 'spatial'
  loss_cfg:
    name: 'torch.nn.CrossEntropyLoss'

  # dataset setting
  dataset_cfg: 
    - name: '.datasets.SkeletonFeeder'
      data_path: ./data/TST_2classes/xsub/train_data.npy
      label_path: ./data/TST_2classes/xsub/train_label.pkl
      # debug: true
    - name: '.datasets.SkeletonFeeder'
      data_path: ./data/TST_2classes/xsub/val_data.npy
      label_path: ./data/TST_2classes/xsub/val_label.pkl
      # debug: true

  # dataloader setting
  batch_size: 1
  gpus: 1

  # optimizer setting
  optimizer_cfg:
    name: 'torch.optim.SGD'
    lr: 0.1
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0001

  # runtime setting
  workflow: [['train', 5], ['val', 1]]
  work_dir: ./work_dir/recognition/st_gcn/xsub
  log_level: 0
  total_epochs: 5
  training_hooks:
    lr_config:
      policy: 'step'
      step: [10, 50]
    log_config:
      interval: 100
      hooks:
        - type: TextLoggerHook
    checkpoint_config:
      interval: 5
    optimizer_config:
  resume_from:
  load_from: